### ISSUE TITLE
web site is offline

### ISSUE THREAD

**Issue by jlopp** [bitcoin-research/bitcoin-research.github.io#35]
bitcoinproblems.org is timing out

Should bitcoin-problems.github.io load? It seems to be unreachable as well

**Comment by ariard** [comment]
@jlopp thanks for reporting. i think @LLFourn can provide feedback.

**Comment by LLFourn** [comment]
Oh thanks for pointing this out. It looks like @nvk has hijacked it and redirected it to coinkite.com to sell more coldcards :laughing:. He was the one who originally bought us the domain. I'm guessing this was an accident.

```
$ curl -vvv  bitcoinproblems.org
*   Trying 75.126.104.235:80...
* Connected to bitcoinproblems.org (75.126.104.235) port 80 (#0)
> GET / HTTP/1.1
> Host: bitcoinproblems.org
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Tue, 10 Sep 2024 01:17:51 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Location: https://coinkite.com
< Strict-Transport-Security: max-age=0;
< 
                                          
```

**Comment by nvk** [comment]
😂😂😂😂

I think that must have been bulk redirected.

We have one or two domains.

Let me ask the team to check

**Comment by nvk** [comment]
Bitcoin might have one less problem. 

Propagating.

```
Type,Host,Answer,TTL,Priority
A,*.bitcoinproblems.org,75.126.104.235,300,
A,bitcoinproblems.org,185.199.108.153,300,
A,bitcoinproblems.org,185.199.109.153,300,
A,bitcoinproblems.org,185.199.110.153,300,
A,bitcoinproblems.org,185.199.111.153,300,
```

**Comment by LLFourn** [comment]
Problem solved! Thanks @nvk.

**Comment by nvk** [comment]
I guess we can solve all bitcoin problems, one by one

**Comment by ariard** [comment]
> I guess we can solve all bitcoin problems, one by one

:thinking_face:
